#!/usr/bin/env perl
use v5.18;
use Pod::Usage qw(pod2usage);
pod2usage( "-verbose" => 2 );

__END__

=head1 Usages

  p5find <object>           Find <object> in current code repository.

  p5find <object> -h        See more deetails about finding <object>

=head1 Objects

p5find can locate various type of objects in the following categories.
Each item in the lists are the name of such object that can be located
by p5find. For example, running C<p5find regex> would list up all
regular expressions under current working directory.

The names these objects also correspond to their specific p5find
commands. For example the command C<p5find-regex> is the one that does
the actual search as well as the one with documentation for its own,
which can be revealed by running C<perldoc p5find-regex>.  The
documentation for all object can also be revealed similarly using
C<perldoc>.

=head2 Primitive types

  - num
  - regex
  - str
  - sub
  - token

=head2 Compound types

  - method-call
  - statement

=head2 Things that should probably be removed

  - unused-package
  - words-used-only-once

Keep in mind that these type of objects depend on the search range (if
you search the entire internet perhaps nothing is unused.).
